#!/bin/bash
# This script provides instructions since we can't fully automate without guest agent

echo "=========================================="
echo "Arch Linux ARM VM Setup Instructions"
echo "=========================================="
echo ""
echo "The VM is now running in UTM. Please follow these steps:"
echo ""
echo "1. Click on the ArchLinux VM in UTM to open the console"
echo "2. Login with: root / root"
echo "3. Run the following commands:"
echo ""
echo "# Install QEMU guest agent and SSH"
echo "pacman -Sy --noconfirm qemu-guest-agent openssh git base-devel sudo vim"
echo ""
echo "# Enable services"
echo "systemctl enable --now qemu-guest-agent"
echo "systemctl enable --now sshd"
echo ""
echo "# Change password"
echo "echo 'root:omarchy' | chpasswd"
echo ""
echo "# Get IP address"
echo "ip -4 addr show | grep inet"
echo ""
echo "After this, you can SSH in and I can continue automated setup!"
echo ""
echo "Or, copy this one-liner:"
echo ""
echo "pacman -Sy --noconfirm qemu-guest-agent openssh git base-devel sudo vim && systemctl enable --now qemu-guest-agent && systemctl enable --now sshd && echo 'root:omarchy' | chpasswd && ip -4 addr show | grep inet"
echo ""
echo "=========================================="

